const prismAliases = {
  // Markup
  '.html': 'markup',
  '.xml': 'markup',
  '.svg': 'markup',
  '.mathml': 'markup',
  '.ssml': 'markup',
  '.atom': 'markup',
  '.rss': 'markup',
  // CSS
  '.css': 'css',
  '.h': 'clike',
  '.hpp': 'clike',
  '.cc': 'clike',
  // JavaScript
  '.js': 'javascript',
  '.abap': 'abap',
  '.abnf': 'abnf',
  '.actionscript': 'actionscript',
  '.ada': 'ada',
  '.agda': 'agda',
  '.al': 'al',
  '.antlr4': 'antlr4',
  '.apacheconf': 'apacheconf',
  '.apex': 'apex',
  '.apl': 'apl',
  '.applescript': 'applescript',
  '.aql': 'aql',
  '.arduino': 'arduino',
  '.arff': 'arff',
  '.armasm': 'armasm',
  '.arturo': 'arturo',
  '.asciidoc': 'asciidoc',
  '.aspnet': 'aspnet',
  '.asm6502': 'asm6502',
  '.asmatmel': 'asmatmel',
  '.autohotkey': 'autohotkey',
  '.autoit': 'autoit',
  '.avisynth': 'avisynth',
  '.avro-idl': 'avro-idl',
  '.awk': 'awk',
  '.bash': ['bash', 'sh', 'shell'],
  '.basic': ['basic'],
  '.batch': ['batch'],
  '.bbcode': ['bbcode', 'shortcode'],
  '.bbj': ['bbj'],
  '.bicep': ['bicep'],
  '.birb': ['birb'],
  '.bison': ['bison'],
  '.bnf': ['bnf', 'rbnf'],
  '.bqn': ['bqn'],
  '.brainfuck': ['brainfuck'],
  '.brightscript': ['brightscript'],
  '.bro': ['bro'],
  '.bsl': ['bsl', 'oscript'],
  '.c': ['c'],
  '.csharp': ['csharp', 'cs', 'dotnet'],
  '.cpp': ['cpp'],
  '.cfscript': ['cfscript', 'cfc'],
  '.chaiscript': ['chaiscript'],
  '.cil': ['cil'],
  '.cilkc': ['cilkc', 'cilk-c'],
  '.cilkcpp': ['cilkcpp', 'cilk-cpp', 'cilk'],
  '.clojure': ['clojure'],
  '.cmake': ['cmake'],
  '.cobol': ['cobol'],
  '.coffeescript': ['coffeescript', 'coffee'],
  '.concurnas': ['concurnas', 'conc'],
  '.csp': ['csp'],
  '.cooklang': ['cooklang'],
  '.coq': ['coq'],
  '.crystal': ['crystal'],
  '.css-extras': ['css-extras'],
  '.csv': ['csv'],
  '.cue': ['cue'],
  '.cypher': ['cypher'],
  '.d': 'd',
  '.dart': 'dart',
  '.dwl': 'dataweave',
  '.dax': 'dax',
  '.dhall': 'dhall',
  '.diff': 'diff',
  '.django': 'django',
  '.jinja2': 'jinja2',
  '.dns': 'dns-zone-file',
  '.zone': 'dns-zone',
  '.dockerfile': 'dockerfile',
  '.dot': 'dot',
  '.gv': 'gv',
  '.ebnf': 'ebnf',
  '.editorconfig': 'editorconfig',
  '.e': 'eiffel',
  '.ejs': 'ejs',
  '.eta': 'eta',
  '.ex': 'elixir',
  '.elm': 'elm',
  '.etlua': 'etlua',
  '.erb': 'erb',
  '.erl': 'erlang',
  '.xlsx': 'excel-formula',
  '.xls': 'excel-formula',
  '.fs': 'fsharp',
  '.factor': 'factor',
  '.firestore': 'firestore-security-rules',
  '.flow': 'flow',
  '.f90': 'fortran',
  '.f95': 'fortran',
  '.ftl': 'ftl',
  '.gml': 'gml',
  '.gap': 'gap',
  '.gcode': 'gcode',
  '.gd': 'gdscript',
  '.ged': 'gedcom',
  '.po': 'gettext',
  '.pot': 'gettext',
  '.feature': 'gherkin',
  '.gitattributes': 'git',
  '.glsl': 'glsl',
  '.gn': 'gn',
  '.gni': 'gn',
  '.linker-script': 'ld',
  '.ld': 'ld',
  '.go': 'go',
  '.go-module': 'go-mod',
  '.go-mod': 'go-mod',
  '.gradle': 'gradle',
  '.graphql': 'graphql',
  '.groovy': 'groovy',
  '.haml': 'haml',
  '.handlebars': 'handlebars',
  '.hbs': 'handlebars',
  '.mustache': 'handlebars',
  '.haskell': 'haskell',
  '.hs': 'haskell',
  '.haxe': 'haxe',
  '.hcl': 'hcl',
  '.hlsl': 'hlsl',
  '.hoon': 'hoon',
  '.http': 'http',
  '.hpkp': 'hpkp',
  '.hsts': 'hsts',
  '.ichigojam': 'ichigojam',
  '.icon': 'icon',
  '.icu-message-format': 'icu-message-format',
  '.idris': 'idris',
  '.idr': 'idris',
  '.ignore': 'ignore',
  '.gitignore': 'gitignore',
  '.hgignore': 'ignore',
  '.npmignore': 'ignore',
  '.inform7': 'inform7',
  '.ini': 'ini',
  '.io': 'io',
  '.j': ['j'],
  '.java': ['java'],
  '.javadoc': ['javadoc'],
  '.javastacktrace': ['javastacktrace'],
  '.jexl': ['jexl'],
  '.jolie': ['jolie'],
  '.jq': ['jq'],
  '.jsdoc': ['jsdoc'],
  '.jsextras': ['js-extras'],
  '.json': ['json', 'webmanifest'],
  '.json5': ['json5'],
  '.jsonp': ['jsonp'],
  '.jsstacktrace': ['jsstacktrace'],
  '.jstemplates': ['js-templates'],
  '.julia': ['julia'],
  '.keepalived': ['keepalived'],
  '.keyman': ['keyman'],
  '.kotlin': ['kotlin', 'kt', 'kts'],
  '.kts': ['kotlin', 'kt', 'kts'],
  '.kumir': ['kumir', 'kum'],
  '.kusto': ['kusto'],
  '.latex': ['latex', 'tex', 'context'],
  '.latte': ['latte'],
  '.less': ['less'],
  '.lilypond': ['lilypond', 'ly'],
  '.liquid': ['liquid'],
  '.lisp': ['lisp', 'emacs', 'elisp', 'emacs-lisp'],
  '.livescript': ['livescript'],
  '.llvm': ['llvm'],
  '.log': ['log'],
  '.lolcode': ['lolcode'],
  '.lua': ['lua'],
  '.magma': ['magma'],
  '.makefile': ['makefile'],
  '.markdown': ['markdown', 'md'],
  '.markup-templating': ['markup-templating'],
  '.mata': ['mata'],
  '.matlab': ['matlab'],
  '.maxscript': ['maxscript'],
  '.mel': ['mel'],
  '.mermaid': ['mermaid'],
  '.metafont': ['metafont'],
  '.mizar': ['mizar'],
  '.mongodb': ['mongodb'],
  '.monkey': ['monkey'],
  '.moonscript': ['moonscript', 'moon'],
  '.pas': 'pascal, objectpascal',
  '.n1ql': 'n1ql',
  '.n4js': 'n4js, n4jsd',
  '.hdl': 'nand2tetris-hdl',
  '.naniscript': 'naniscript, nani',
  '.nasm': 'nasm',
  '.neon': 'neon',
  '.nevod': 'nevod',
  '.nginx': 'nginx',
  '.nim': 'nim',
  '.nix': 'nix',
  '.nsi': 'nsis',
  '.obj-c': 'objectc, objc',
  '.ml': 'ocaml',
  '.odin': 'odin',
  '.cl': 'opencl',
  '.qasm': 'openqasm, qasm',
  '.oz': 'oz',
  '.par': 'parigp',
  '.parser': 'parser',
  '.psl': 'psl',
  '.px': 'pcaxis',
  '.peoplecode': 'peoplecode, pcode',
  '.pl': 'perl',
  '.php': 'php',
  '.phpdoc': 'phpdoc',
  '.puml': 'plant-uml',
  '.plsql': 'plsql',
  '.pq': 'powerquery',
  '.mscript': 'powerquery',
  '.ps1': 'powershell',
  '.psd1': 'powershell',
  '.psm1': 'powershell',
  '.ino': 'processing',
  '.prolog': 'prolog',
  '.promql': 'promql',
  '.properties': 'properties',
  '.pug': 'pug',
  '.pp': 'puppet',
  '.purs': 'purescript',
  '.pure': 'pure',
  '.pb': 'purebasic',
  '.py': 'python',
  '.qs': 'qsharp',
  '.qml': 'qml',
  '.q': 'q',
  '.rkt': 'racket',
  '.razor': 'razor',
  '.jsx': 'jsx',
  '.tsx': 'tsx',
  '.re': 'reason',
  '.rego': 'rego',
  '.rpy': 'renpy',
  '.res': 'rescript',
  '.rest': 'rest',
  '.robot': 'robotframework',
  '.rb': 'ruby',
  '.rs': 'rust',
  '.sas': 'sas',
  '.sass': 'sass',
  '.scss': 'scss',
  '.scala': 'scala',
  '.scm': 'scheme',
  '.shell-session': 'shell-session',
  '.sh-session': 'sh-session',
  '.smali': 'smali',
  '.smalltalk': 'smalltalk',
  '.tpl': 'smarty',
  '.sml': 'sml',
  '.sol': 'solidity',
  '.sln': 'solution-file',
  '.soy': 'soy',
  '.rq': 'sparql',
  '.spl': 'splunk-spl',
  '.sqf': 'sqf',
  '.sql': 'sql',
  '.nut': 'squirrel',
  '.stan': 'stan',
  '.ado': 'stata',
  '.st': 'iecst',
  '.styl': 'stylus',
  '.sc': 'supercollider',
  '.swift': 'swift',
  '.service': 'systemd',
  '.tt': 't4-templating',
  '.t4': 't4-cs',
  '.tap': 'tap',
  '.tcl': 'tcl',
  '.tt2': 'tt2',
  '.textile': 'textile',
  '.toml': 'toml',
  '.trickle': 'tremor',
  '.ttl': 'turtle',
  '.twig': 'twig',
  '.ts': 'typescript',
  '.typoscript': 'typoscript',
  '.us': 'unrealscript',
  '.uc': 'unrealscript',
  '.uri': 'uri',
  '.url': 'uri',
  '.v': 'v',
  '.vala': 'vala',
  '.vb': 'vbnet',
  '.vba': 'visual-basic',
  '.velocity': 'velocity',
  '.vhd': 'vhdl',
  '.vim': 'vim',
  '.wsp': 'warpscript',
  '.wasm': 'wasm',
  '.webidl': 'web-idl',
  '.wgsl': 'wgsl',
  '.wiki': 'wiki',
  '.nb': 'wolfram',
  '.wl': 'wolfram',
  '.wren': 'wren',
  '.xeo': 'xeora',
  '.xml-doc': 'markup',
  '.xq': 'xquery',
  '.xquery': 'xquery',
  '.yaml': 'yaml',
  '.yang': 'yang',
  '.zig': 'zig'
}

const mappings = {}
// loop through all the extensions in prismAliases and if the mapping is an array, add only the first item
for (let [key, value] of Object.entries(prismAliases)) {
  if (Array.isArray(value)) {
    mappings[key] = value[0]
  } else {
    mappings[key] = value
  }
}
// sort mappings
const sorted = {}
Object.keys(mappings)
  .sort()
  .forEach(function (key) {
    sorted[key] = mappings[key]
  })

// if mapping key is same as value, delete it and add the key to the array simple
const simple = []
for (let [key, value] of Object.entries(sorted)) {
  // compare key without leading "." char
  if (key.slice(1) === value) {
    simple.push(key)
    delete sorted[key]
  }
}

console.log(JSON.stringify(sorted, null, 2))

// loop through simple and output array of doubel quoted strings
const simpleOutput = []
for (let [key, value] of Object.entries(simple)) {
  simpleOutput.push(`"${value}"`)
}
console.log(simpleOutput.join(', '))
