import path from 'path';

const mappings = {
  '.gitignore': 'ignore',
  '.ado': 'stata',
  '.atom': 'markup',
  '.cc': 'clike',
  '.cl': 'opencl',
  '.dns': 'dns-zone-file',
  '.dwl': 'dataweave',
  '.drawio': 'markup',
  '.e': 'eiffel',
  '.erl': 'erlang',
  '.ex': 'elixir',
  '.f90': 'fortran',
  '.f95': 'fortran',
  '.feature': 'gherkin',
  '.firestore': 'firestore-security-rules',
  '.fs': 'fsharp',
  '.gd': 'gdscript',
  '.ged': 'gedcom',
  '.gitattributes': 'git',
  '.gni': 'gn',
  '.go-module': 'go-mod',
  '.h': 'clike',
  '.hbs': 'handlebars',
  '.hdl': 'nand2tetris-hdl',
  '.hgignore': 'ignore',
  '.hpp': 'clike',
  '.hs': 'haskell',
  '.html': 'markup',
  '.idr': 'idris',
  '.ino': 'processing',
  '.js': 'javascript',
  '.jsextras': 'js-extras',
  '.jstemplates': 'js-templates',
  '.kts': 'kotlin',
  '.linker-script': 'ld',
  '.mathml': 'markup',
  '.md': 'markdown',
  '.ml': 'ocaml',
  '.mscript': 'powerquery',
  '.mustache': 'handlebars',
  '.n4js': 'n4js, n4jsd',
  '.naniscript': 'naniscript, nani',
  '.nb': 'wolfram',
  '.npmignore': 'ignore',
  '.nsi': 'nsis',
  '.nut': 'squirrel',
  '.obj-c': 'objectc, objc',
  '.par': 'parigp',
  '.pas': 'pascal, objectpascal',
  '.pb': 'purebasic',
  '.peoplecode': 'peoplecode, pcode',
  '.pl': 'perl',
  '.po': 'gettext',
  '.pot': 'gettext',
  '.pp': 'puppet',
  '.pq': 'powerquery',
  '.ps1': 'powershell',
  '.psd1': 'powershell',
  '.psm1': 'powershell',
  '.puml': 'plant-uml',
  '.purs': 'purescript',
  '.px': 'pcaxis',
  '.py': 'python',
  '.qasm': 'openqasm, qasm',
  '.qs': 'qsharp',
  '.rb': 'ruby',
  '.re': 'reason',
  '.res': 'rescript',
  '.rkt': 'racket',
  '.robot': 'robotframework',
  '.rpy': 'renpy',
  '.rq': 'sparql',
  '.rs': 'rust',
  '.rss': 'markup',
  '.sc': 'supercollider',
  '.scm': 'scheme',
  '.service': 'systemd',
  '.sln': 'solution-file',
  '.sol': 'solidity',
  '.spl': 'splunk-spl',
  '.ssml': 'markup',
  '.st': 'iecst',
  '.styl': 'stylus',
  '.svg': 'markup',
  '.t4': 't4-cs',
  '.tpl': 'smarty',
  '.trickle': 'tremor',
  '.ts': 'typescript',
  '.tt': 't4-templating',
  '.ttl': 'turtle',
  '.uc': 'unrealscript',
  '.url': 'uri',
  '.us': 'unrealscript',
  '.vb': 'vbnet',
  '.vba': 'visual-basic',
  '.vhd': 'vhdl',
  '.vue': 'markup',
  '.webidl': 'web-idl',
  '.wl': 'wolfram',
  '.wsp': 'warpscript',
  '.xeo': 'xeora',
  '.xls': 'excel-formula',
  '.xlsx': 'excel-formula',
  '.xml': 'markup',
  '.xml-doc': 'markup',
  '.xq': 'xquery',
  '.zone': 'dns-zone'
}
const identical = [
  '.abap',
  '.abnf',
  '.actionscript',
  '.ada',
  '.agda',
  '.al',
  '.antlr4',
  '.apacheconf',
  '.apex',
  '.apl',
  '.applescript',
  '.aql',
  '.arduino',
  '.arff',
  '.armasm',
  '.arturo',
  '.asciidoc',
  '.asm6502',
  '.asmatmel',
  '.aspnet',
  '.autohotkey',
  '.autoit',
  '.avisynth',
  '.avro-idl',
  '.awk',
  '.bash',
  '.basic',
  '.batch',
  '.bbcode',
  '.bbj',
  '.bicep',
  '.birb',
  '.bison',
  '.bnf',
  '.bqn',
  '.brainfuck',
  '.brightscript',
  '.bro',
  '.bsl',
  '.c',
  '.cfscript',
  '.chaiscript',
  '.cil',
  '.cilkc',
  '.cilkcpp',
  '.clojure',
  '.cmake',
  '.cobol',
  '.coffeescript',
  '.concurnas',
  '.cooklang',
  '.coq',
  '.cpp',
  '.crystal',
  '.csharp',
  '.csp',
  '.css',
  '.css-extras',
  '.csv',
  '.cue',
  '.cypher',
  '.d',
  '.dart',
  '.dax',
  '.dhall',
  '.diff',
  '.django',
  '.dockerfile',
  '.dot',
  '.ebnf',
  '.editorconfig',
  '.ejs',
  '.elm',
  '.erb',
  '.eta',
  '.etlua',
  '.factor',
  '.flow',
  '.ftl',
  '.gap',
  '.gcode',
  '.gitignore',
  '.glsl',
  '.gml',
  '.gn',
  '.go',
  '.go-mod',
  '.gradle',
  '.graphql',
  '.groovy',
  '.gv',
  '.haml',
  '.handlebars',
  '.haskell',
  '.haxe',
  '.hcl',
  '.hlsl',
  '.hoon',
  '.hpkp',
  '.hsts',
  '.http',
  '.ichigojam',
  '.icon',
  '.icu-message-format',
  '.idris',
  '.ignore',
  '.inform7',
  '.ini',
  '.io',
  '.j',
  '.java',
  '.javadoc',
  '.javastacktrace',
  '.jexl',
  '.jinja2',
  '.jolie',
  '.jq',
  '.jsdoc',
  '.json',
  '.json5',
  '.jsonp',
  '.jsstacktrace',
  '.jsx',
  '.julia',
  '.keepalived',
  '.keyman',
  '.kotlin',
  '.kumir',
  '.kusto',
  '.latex',
  '.latte',
  '.ld',
  '.less',
  '.lilypond',
  '.liquid',
  '.lisp',
  '.livescript',
  '.llvm',
  '.log',
  '.lolcode',
  '.lua',
  '.magma',
  '.makefile',
  '.markdown',
  '.markup-templating',
  '.mata',
  '.matlab',
  '.maxscript',
  '.mel',
  '.mermaid',
  '.metafont',
  '.mizar',
  '.mongodb',
  '.monkey',
  '.moonscript',
  '.n1ql',
  '.nasm',
  '.neon',
  '.nevod',
  '.nginx',
  '.nim',
  '.nix',
  '.odin',
  '.oz',
  '.parser',
  '.php',
  '.phpdoc',
  '.plsql',
  '.prolog',
  '.promql',
  '.properties',
  '.psl',
  '.pug',
  '.pure',
  '.q',
  '.qml',
  '.razor',
  '.rego',
  '.rest',
  '.sas',
  '.sass',
  '.scala',
  '.scss',
  '.sh-session',
  '.shell-session',
  '.smali',
  '.smalltalk',
  '.sml',
  '.soy',
  '.sqf',
  '.sql',
  '.stan',
  '.swift',
  '.tap',
  '.tcl',
  '.toml',
  '.tsx',
  '.tt2',
  '.twig',
  '.typoscript',
  '.uri',
  '.v',
  '.vala',
  '.velocity',
  '.vim',
  '.wasm',
  '.wgsl',
  '.wiki',
  '.wren',
  '.xquery',
  '.yaml',
  '.yang',
  '.zig'
]

export function fileExtToPrismAlias(fileName: string): string {
  if (fileName[0] === '.') {
    // because path.extname('.c') weirdly gives '', workaround this
    fileName = 'x' + fileName
  }
  const ext = path.extname(fileName)
  if (ext === '') {
    console.log('returning empty string', fileName, ext)
    return ''
  }
  console.log('is ext in mappings', ext in mappings, ext, mappings[ext])
  if (ext in mappings) {
    return mappings[ext]
  }
  if (identical.includes(ext)) {
    return ext.slice(1)
  }
  return ''
}
